version: 0.2

phases:
  build:
    commands:
      - aws s3 cp index.html s3://luit-gold-march-2024-beta --acl public-read
      - |
        if [ "$CODEBUILD_SOURCE_VERSION_TYPE" == "pull_request_merged" ]; then
            aws s3 cp index.html s3://luit-gold-march-2024-gold --acl public-read
        fi
